### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by elsehow** [bknarendra/fb_photo_friend_finder#1]
Here's what I see when I run the script, after following instructions:

```
uploading file: downloaded-fb-photo.jpg
/Library/Ruby/Gems/2.0.0/gems/koala-2.3.0/lib/koala/api/graph_api.rb:529:in `block in graph_call': type: OAuthException, code: 200, message: (#200) Requires extended permission: publish_actions, x-fb-trace-id: GZqseFBJGKw [HTTP 403] (Koala::Facebook::ClientError)
    from /Library/Ruby/Gems/2.0.0/gems/koala-2.3.0/lib/koala/api.rb:80:in `api'
    from /Library/Ruby/Gems/2.0.0/gems/koala-2.3.0/lib/koala/api/graph_api.rb:527:in `graph_call'
    from /Library/Ruby/Gems/2.0.0/gems/koala-2.3.0/lib/koala/api/graph_api.rb:148:in `put_connections'
    from /Library/Ruby/Gems/2.0.0/gems/koala-2.3.0/lib/koala/api/graph_api.rb:236:in `put_picture'
    from photo_friend_finder.rb:18:in `<main>'
```

One place I think I may have gone wrong is in copying the cookie. I did it like this:

``` ruby
COOKIES = "cookie: datr=...0467F2CC"
```

Am I missing something?

**Comment by bknarendra** [comment]
No its not the issue of cookies. It is the issue with the access token. Did you allow all the permissions when the opened the link for generating access token?

**Comment by elsehow** [comment]
Here are the steps I took
- Removed access from the photo finder app in my Facebook settings (for a fresh start)
- Followed the link in the README
- Saw this notice: 

```
Continue as Nick
Photo Friend Finder will receive the following info: your public profile. 
Review the info you provide
[...]
Public profile
Nick Merrill, profile picture, 21+ years old, male and other public info

This does not let the app post to Facebook."
```
- Clicked OK
- Quickly copied the URL before it redirected me to a page that told me never to tell anyone my URL :)
- Copied the token from the query param into the ruby script as instructed.

The error persists, though.

It doesn't look like I'm being asked for upload permissions when I follow the link to allow app access.

**Comment by bknarendra** [comment]
It might be because my app review is still not done. So it doesn't have authority to ask for permissions to publish_actions and user_photos. So it might be better to just create your own app, or use the graph api explorer access token. You can use any access token just make sure it has the permissions publish_actions and user_photos.

**Comment by elsehow** [comment]
Got it, thanks!

**Comment by elsehow** [comment]
That worked. Opening up a PR with new instructions in the README.
